
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"Alex-AnnouncementsBackend","number":41,"title":"Created entity and repository files for Announcement","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/41"},{"author":{"id":"MDQ6VXNlcjg3MDUzMjc1","is_bot":false,"login":"hancheng-li","name":""},"headRefName":"Hancheng-sorting","number":38,"title":"Hancheng sorting","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/38"},{"author":{"id":"MDQ6VXNlcjM1MjY0NzIx","is_bot":false,"login":"alexkxu","name":"Alex Xu"},"headRefName":"Alex-gameInProgress()","number":37,"title":"Implemented gameInProgress() under Commons entity, and tests","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/37"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-spike-sort","number":34,"title":"Pc spike sort","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-FarmerGreetingMessages","number":30,"title":"New and Improved Farmer Greeting Messages","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/30"}]
