
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/proj-happycows-f23-5pm-2
owner: ucsb-cs156-f23
repo_name: proj-happycows-f23-5pm-2
pull_requests: [{"author":{"id":"U_kgDOBh9GEw","is_bot":false,"login":"ChinDandekar","name":"ChinDandekar"},"headRefName":"chinmay-refactor-chat","number":36,"title":"Chinmay - refactor chattoggle from PlayPage.js into it's own React Component","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/36"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"adam-default-backend","number":35,"title":"Added customizable default values for creating a new commons","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/35"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-spike-sort","number":34,"title":"Pc spike sort","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjcyODI1MTEz","is_bot":false,"login":"amgadhawari","name":""},"headRefName":"Amgad-FarmerGreetingMessages","number":30,"title":"New and Improved Farmer Greeting Messages","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/30"},{"author":{"id":"MDQ6VXNlcjcyOTAzNjE1","is_bot":false,"login":"akainu11","name":"Adam Nobunaga"},"headRefName":"leaderboard-ux","number":25,"title":"Updated the leaderboard and added tests","url":"https://github.com/ucsb-cs156-f23/proj-happycows-f23-5pm-2/pull/25"}]
